server:
  port: 8086

spring:
  datasource:
    url: jdbc:mariadb://localhost:2206/admin
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernage.SQL: debug
    org:
      hibernage:
        type: trace
