server:
  port: 8086

spring:
    datasource:
      url: ${url:jdbc:mariadb://localhost:3308/admin}
      username: root
      password: root1234
      driver-class-name: org.mariadb.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          default_batch_fetch_size: 1000

logging:
  level:
    org.hibernage.SQL: debug
    org:
      hibernage:
        type: trace
